MJPEG Rewrite
opensight-cv/opensight pull request #48
Opened 2020-04-14 10:05 UTC by 132ikl

2020-04-14 18:53 UTC, dzil123 requested changes

2020-04-14 18:53 UTC, dzil123 commented on opsi/modules/videoio/mjpeg.py
> +        params = {"compression": 70, "fps": 30, "resolution": None}
Consider using a dataclass

2020-04-14 18:53 UTC, dzil123 commented on opsi/modules/videoio/mjpeg.py
> +        params["fps"] = self.int_param("fps", 30)
I don't like that you have defaults in two places, in the initial `params` declaration and in each `int_param`

2020-04-14 18:53 UTC, dzil123 commented on opsi/modules/videoio/mjpeg.py
> +        params["compression"] = self.int_param("compression", 30)
Also this default compression=30 is different from the other default compression=70

2020-04-14 18:53 UTC, dzil123 commented on opsi/modules/videoio/mjpeg.py
> +        self.pendingFrame = False
`pendingFrame` is never used

2020-04-15 08:35 UTC, dzil123 approved these changes

2020-04-15 08:35 UTC, dzil123 approved these changes

2020-04-15 08:35 UTC, merged

2020-04-15 08:36 UTC, dzil123 commented
Why did you do two reviews smh

2020-04-15 08:36 UTC, 132ikl commented
i didn't :flushed:

2020-04-15 08:36 UTC, dzil123 commented
Oh wait that was me haha